### ISSUE TITLE
compile to .COM/.EXE file?

### ISSUE THREAD

**Issue by aquynh** [icebreaker/floppybird#2]
this is such a great work! a question: can you have Makefile to compile this to .COM (or .EXE) file, so it is possible to run the game under DosBox/DosEmu?

thanks.

**Comment by icebreaker** [comment]
@aquynh Not at the moment, but I will make it happen in the next few days. :)

By the way "capstone engine" looks awesome.

**Comment by aquynh** [comment]
yes please! so it is possible to play this game without needing a full OS.

yes Capstone is becoming a standard disassembly engine now. check it out :-)

**Comment by icebreaker** [comment]
You can still try it out in the meantime with QEMU or VirtualBox :)

**Comment by icebreaker** [comment]
Alright @aquynh , if you pull the latest "master" you should be able to build it and run it via:

```bash
make com
make dosbox
```

Enjoy this little *bonus* :) :secret:
