### ISSUE TITLE
Floppybird OS inside a BIOS chip - is working great ;-)

### ISSUE THREAD

**Issue by informer2016** [icebreaker/floppybird#3]
Even today the floppies are still being used, for example - as virtual floppies inside the coreboot open source BIOS. Just imagine: your wonderful OS could be a part of someone's BIOS build! _(for coreboot supported motherboard, maybe you have or could get one - see https://www.coreboot.org/Supported_Motherboards )_

If you already have a coreboot-supported motherboard, or a real chance to get one, - wouldn't it be cool to be able to launch your own OS straight from the BIOS chip? ;) With one simple command it is possible to add any floppy to coreboot BIOS build - and then you see it as a boot entry. Multiple floppies could be added this way _(as long as you have enough space left inside the BIOS flash chip, luckily LZMA compression could be used for the stored floppies to reduce their occupied size)_ - although with the unofficial SeaBIOS multiple floppies patch found here - http://dangerousprototypes.com/docs/Lenovo_G505S_hacking#Unofficial_SeaBIOS_patches .

@icebreaker , my sincere congratulations: I added your FloppyBird compiled image (uploaded by my friend here - https://github.com/mikebdp2/floparchive/blob/master/floppies_extra/floppybird.img ) to the coreboot.rom BIOS build for my Lenovo G505S , and it's working perfectly :wink: Also, after LZMA compression your FloppyBird occupies just 2174 bytes inside the flash chip. Thank you very much for this beautiful game, Mihail, it made my BIOS better and funnier :+1:

**Comment by icebreaker** [comment]
I only tried it on a few actual physical machines, I am very surprised that it still works on relatively modern hardware such as the G505S.

**Comment by informer2016** [comment]
@icebreaker Works maybe because SeaBIOS - default coreboot's payload _(coreboot itself just initializes the hardware then gives a control to payload)_ which I'm using - is modern "legacy-style" BIOS, not UEFI. Thank you very much for your Floppybird OS, this perfect addition to a BIOS. Have a nice day ;-)

**Comment by informer2016** [comment]
@icebreaker I am attaching the latest FloppybirdOS build here - [floppybird.zip](https://github.com/icebreaker/floppybird/files/3260222/floppybird.zip) Hopefully you could put it into "Releases" ! SHA256 checksums:
```
5db1b469e25e9eda7b8c0f666d6b655bab083c85618a9453ee72f1201cca840f  ./floppybird.img
6227b9399b244d264382ef14626565e84147ce1ba16cb244f6020395e057a5fd  ./floppybird.zip
```
